var Level={pieces:null,levels:null,grid:[],cols:0,name:"",startX:0,startY:0,totalCoins:0};
Level.setStatus=function(t){var e=document.getElementById("status");if(e)e.textContent=t;};
Level.loadData=function(done){Level.setStatus("Loading pieces...");fetch("data/pieces.json").then(function(r){if(!r.ok)throw Error("pieces.json HTTP "+r.status);return r.json();}).then(function(p){Level.pieces=p;Level.setStatus("Loading levels...");return fetch("data/levels.json");}).then(function(r){if(!r.ok)throw Error("levels.json HTTP "+r.status);return r.json();}).then(function(f){if(!f.levels||!f.levels.length)throw Error("levels.json has no levels");Level.levels=f.levels;done();}).catch(function(e){Level.setStatus("Game failed: data could not load");var m=document.getElementById("message");if(m)m.textContent="Check that you opened the game through HTTP (not file://).";console.error(e);});};
Level.build=function(n){var l=Level.levels[n];if(!l)throw Error("Missing level "+n);Level.name=l.name;Level.grid=[];Level.cols=l.pieces.length*CONFIG.PIECE_COLS;for(var r=0;r<CONFIG.ROWS;r++)Level.grid[r]="";for(var p=0;p<l.pieces.length;p++){var piece=Level.pieces[l.pieces[p]]||Level.pieces.flat;if(!piece||piece.length!==CONFIG.ROWS)throw Error("Invalid piece: "+l.pieces[p]);for(var r2=0;r2<CONFIG.ROWS;r2++)Level.grid[r2]+=piece[r2];}Level.findStart();Level.countCoins();};
Level.findStart=function(){for(var r=0;r<CONFIG.ROWS;r++)for(var c=0;c<Level.cols;c++)if(Level.charAt(c,r)==="S"){Level.startX=c*CONFIG.TILE;Level.startY=r*CONFIG.TILE;return;}Level.startX=0;Level.startY=0;};
Level.countCoins=function(){Level.totalCoins=0;for(var r=0;r<CONFIG.ROWS;r++)for(var c=0;c<Level.cols;c++)if(Level.charAt(c,r)==="C")Level.totalCoins++;};
Level.removeCoin=function(c,r){var s=Level.grid[r];Level.grid[r]=s.slice(0,c)+"."+s.slice(c+1);};
Level.charAt=function(c,r){return r<0||r>=CONFIG.ROWS||c<0||c>=Level.cols?".":Level.grid[r].charAt(c);};
Level.isSolid=function(c,r){return Level.charAt(c,r)==="#";};Level.isSpike=function(c,r){return Level.charAt(c,r)==="^";};Level.isCoin=function(c,r){return Level.charAt(c,r)==="C";};Level.isFinish=function(c,r){return Level.charAt(c,r)==="F";};Level.pixelWidth=function(){return Level.cols*CONFIG.TILE;};
